name: Trigger auto deployment for aca-vmm-containerapp-new

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-vmm-containerapp-new-AutoDeployTrigger-7c5dba76-ad23-4177-b631-267ce41ec7d3.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAVMMCONTAINERAPPNEW_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: kiranreg.azurecr.io
          registryUsername: ${{ secrets.ACAVMMCONTAINERAPPNEW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAVMMCONTAINERAPPNEW_REGISTRY_PASSWORD }}
          containerAppName: aca-vmm-containerapp-new
          resourceGroup: kirancontainer
          imageToBuild: kiranreg.azurecr.io/aca-vmm-containerapp-new:${{ github.sha }}
          
            

     

